A = 1;
B = 8;
C = 3;
D = 6;
E = 2;
F = 0;
G = 7;
H = 1;
a1 = D+H;
a2 = E+H;
a3 = F+H;
f1 = G+H;
f2 = F+H;
f3 = E+H;
s = (H/4 + 1);
y = a1*sin(2*pi*f1*t) + a2*cos(2*pi*f2*t-60) - a3*sin(2*pi*f3*t);
noise_signal = s*randn(size(t));
powfund = sum(y.^2) / length(y);
varnoise = sum(noise_signal.^2) /length(noise_signal);
%varnoise = s^2;
SNR = snr(y, noise_signal)  
defSNR = 10*log10(powfund/varnoise)